### ISSUE TITLE
Release fixes since last release

### ISSUE THREAD

**Issue by rjurney** [Unidata/siphon#149]
It would be great if you could cut a release, as we noticed a fix that you recently committed (that I can't find, but it was related to our GFS connectivity). When do you plan to release? I tried installing `siphon` from source, but that caused a cascade of problems with dependencies in our project and so it did not work out.

**Comment by dopplershift** [comment]
So we released 0.5 last month, and there have only been 6 (minor) commits since then, so there must be something amiss with how you're trying to update. 

Out of curiosity, have you installed siphon using conda, but from the old Unidata channel? (You can check this with `conda config --get channels`) If so, you should move to use the conda-forge channel, as that's where the most recent releases will appear. Either do:
```
conda config --add channels conda-forge
conda update siphon
```
to add conda-forge permanently to your list of channels, or install siphon directly from the conda-forge channel with:
```
conda install -c conda-forge siphon
```

**Comment by jrleeman** [comment]
@rjurney - Wanted to check in on this and see if installing from condo forge fixed your issue.

**Comment by jrleeman** [comment]
Siphon 0.6 is being released today (9/15/17) - Closing
