### ISSUE TITLE
Add IGRA2 upper air archive

### ISSUE THREAD

**Issue by DanielWatkins** [Unidata/siphon#178]
The Integrated Global Radiosonde Archive contains thousands of quality controlled radiosonde soundings, which are available from an NCEI ftp. It would be nice to have a function similar to the Wyoming upper air function for IGRA2.

**Comment by dopplershift** [comment]
Sounds interesting. With the current backlog, it will be awhile before we get around to looking at it. Would you be interested in working up a pull request to do it?

**Comment by DanielWatkins** [comment]
Yes, and I have some code written for processing the IGRA data so at least part of the task would be mostly done already. I know for the Wyoming data you can just read off a webpage so there is no need for writing files. For IGRA though the files are zip files on an ftp, so I set up code to download and unpack the zip file, then make a pandas dataframe by reading from the downloaded text file. Would that kind of approach fit siphon? Or is siphon supposed to only have stuff that you can read remotely without saving onto a computer?

**Comment by dopplershift** [comment]
I'd prefer to avoid saving it to the local computer (unless the user actually wants it there) because then you have to manage cleaning up after yourself. It looks like python's [zipfile](https://docs.python.org/3/library/zipfile.html#zipfile-objects) module can read from file-like objects, which *should* let you read without explicitly saving to disk.

If that doesn't work, it's not a dealbreaker, though. We end up doing that internally with netCDF files, for now at least.

**Comment by DanielWatkins** [comment]
Right, that should work! I'll give it a try.
