### ISSUE TITLE
Failure to get access urls

### ISSUE THREAD

**Issue by jrleeman** [Unidata/siphon#179]
In moving things from NOMADS to NCEI we're failing to return any access urls. Not sure if it's a siphon or NCEI issue yet.

Broken example:

```python
from siphon.catalog import TDSCatalog
base_url = 'https://www.ncei.noaa.gov/thredds/catalog/namanl/'
dt = datetime(2011, 4, 27)
cat = TDSCatalog('{}{dt:%Y%m}/{dt:%Y%m%d}/catalog.xml'.format(base_url, dt=dt))
ds = cat.datasets[0]
print(ds.access_urls)
```

**Comment by dopplershift** [comment]
So the problem is caused by the following:
```xml
<metadata inherited="true">
<serviceName>ALL</serviceName>
<authority>gov.noaa.ncdc</authority>
<dataType>GRID</dataType>
<documentation type="funding">
U.S. Climate Program Office (reanalysis grant), EMC, CPC, NCEP Central Operations (NCO), and NESDIS
</documentation>
<documentation type="processing_level">Level 4</documentation>
<documentation type="rights">
Electronic downloads of the data are free, however fees apply for data certification and distribution of the data on physical media. Fees vary based on order specifications.
</documentation>
<creator>
<name vocabulary="GCMD">DOC/NOAA/NWS/NCEP</name>
<contact url="http://www.ncep.noaa.gov/" email="http://www.ncep.noaa.gov/mail_liaison/"/>
</creator>
<keyword vocabulary="GCMD">
GOVERNMENT AGENCIES-U.S. FEDERAL AGENCIES, DOC, NOAA, DOC/NOAA/NESDIS/NCEI, National Centers for Environmental Information, NESDIS, U.S. Department of Commerce, EARTH SCIENCE SERVICES, MODELS, EARTH SCIENCE REANALYSES/ASSIMILATION MODELS
</keyword>
<metadata xlink:href="http://gis.ncdc.noaa.gov/geoportal/rest/document?id={6439CC43-0208-4AD6-BF6F-48F586F7541D}" xlink:title="ISO 19115-2:2009(E) - Collection Level Metadata"/>
<project>North American Mesoscale</project>
<publisher>
<name vocabulary="GCMD">DOC/NOAA/NESDIS/NCEI</name>
<contact url="https://www.ncei.noaa.gov/" email="ncei.info@noaa.gov"/>
</publisher>
</metadata>
```
Note the nested metadata element. Where this breaks is:
https://github.com/Unidata/siphon/blob/935d195272deb016e2816d256b83c8e3b1dd16b0/siphon/metadata.py#L468-L481

The combination of defaulting to `False` for "inherited" the metadata, together with only keeping the parent metadata if "inherited" is `True` causes us to ditch the parent metadata. Of course, the real problem might be at:

https://github.com/Unidata/siphon/blob/935d195272deb016e2816d256b83c8e3b1dd16b0/siphon/catalog.py#L259-L262

where the `TDSCatalog` decides to unconditionally take whatever metadata comes in after parsing a child tag. @lesserwhirls any thoughts here?

If I just force the use of the initial metadata tag, the bug goes away, so it's definitely a problem in how the metadata is processed--I just don't know what the proper handling is here.

**Comment by lesserwhirls** [comment]
Hmmm. According to the [xsd](https://www.unidata.ucar.edu/software/thredds/v4.6/tds/catalog/InvCatalogSpec.html#metadataElement)"

>A metadata element contains any number of elements from the threddsMetadataGroup in any order, OR it contains any other well-formed XML elements, as long as they are in a namespace other than the THREDDS namespace.

That would seem to say that a `metadata` element cannot have a `metadata` child. But, then again:

>It may also contain an XLink to another XML document, whose top-level element should be a valid metadata element (see example below).

Now this isn't super clear. It sounds like it is saying that the metadata element can include xlink attributes that point to an external xml doc, assuming the top level element of the external doc is a valid metadata element, but it does not sound like the metadata parent/child situation is actually covered.

Maybe in a previous life a metadata element could have a child metadata element? @ethanrd?

As for what to do...probably need to think about that one some more. 

Maybe instead of accepting whatever comes back from `TDSCatalogMetadata`, we could check if `self.metadata` is empty, and if not, extend the dict with what comes back? We would need to allow `TDSCatalogMetadata` to parse a `metadata` element, check to see if it is an xlink, and add an appropriate `key:value` for it (I'd say if it isn't a xlink, log it as a warning and skip it?).

**Comment by dopplershift** [comment]
I think it also bears noting that clearly this doesn’t break the Java catalog code.

**Comment by ethanrd** [comment]
A `metadata` element is just a container for information. They may be nested (they may contain elements from the `threddsMetadatGroup` which includes the `metadata` element). Rather than directly containing other information, they may reference external `metadata` XML resources (the contents of which should be treated as though it were directly contained).

It was meant to be a very general structure to allow data providers to include whatever metadata they thought they needed.

**Comment by dopplershift** [comment]
Here's an actual link to the catalog in question: https://www.ncei.noaa.gov/thredds/catalog/namanl/201802/20180220/catalog.html
