### ISSUE TITLE
Suport netCDFServer name

### ISSUE THREAD

**Issue by jrleeman** [Unidata/siphon#215]
When using NCEI data, they use the older name for NCSS. This makes workshop materials more complicated and requires too much knowledge of the data source for users. We thought this was in 0.7 😭

**Comment by lesserwhirls** [comment]
There are a couple of ways to go about this. Probably the best way, from an end users point of view, would would involve making sure that this _just works_&copy;&trade;&reg;:

~~~python
ncss = dataset.subset()
~~~

To do so, we could add a check in the `KeyError` except:

https://github.com/Unidata/siphon/blob/935d195272deb016e2816d256b83c8e3b1dd16b0/siphon/catalog.py#L592-L596

and check to see if 

1) `service` is `NetcdfSubset` and 
2) if `self.access_urls` contains `NetcdfServer` 

If both are true, then we use use `NetcdfServer` as the `service`. Otherwise, raise the `ValueError` as we currently do.

**Comment by dopplershift** [comment]
See #215 for what seemed to be least horrible to me.
