### ISSUE TITLE
Going from TDSCatalog to pandas via xarray uses excessive memory

### ISSUE THREAD

**Issue by sgdecker** [Unidata/siphon#304]
I think this is related to #289, perhaps?

```python
from siphon.catalog import TDSCatalog

sfc_obs = TDSCatalog('https://thredds.ucar.edu/thredds/catalog/'
                     'nws/metar/ncdecoded/files/catalog.xml')
dataset = sfc_obs.datasets[1]
ncdata = dataset.remote_access(use_xarray=True)
df = ncdata.to_dataframe()
```
- Problem description:
The code above gives me:
```
fish: Job 2, “python bug.py” terminated by signal SIGKILL (Forced quit)
```
with `top` showing me that all the memory is being consumed on my machine.
- Expected output
A Pandas dataframe full of surface observations from a particular date.
- Which platform
Linux
- Versions
Python: 3.8.1
Siphon: 0.8.0

**Comment by dopplershift** [comment]
Actually, this is unrelated to #289, since that's only about downloading over HTTP/`remote_open()`.

Here everything seems fine until you call `to_dataframe()`. I can actually reproduce this without Siphon at all:
```python
import xarray as xr
ncdata = xr.open_dataset('https://thredds.ucar.edu/thredds/dodsC/nws/metar/ncdecoded/files/Surface_METAR_20200411_0000.nc')
df = ncdata.to_dataframe()
```

I'm pretty sure there's a bug, because the netCDF files are only ~50M on disk, so there's no reason they should be exhausting memory--but the bug isn't in Siphon. Can you open this upstream in xarray?

**Comment by sgdecker** [comment]
Ahh, yes, I see that as well. In fact, I got a more informative error this time:
```
MemoryError: Unable to allocate array with shape (117819, 5021) and data type |S64
```
If I'm doing the math right, that's something like 35 GB that is trying to be allocated.

I'll open an xarray issue.

**Comment by dopplershift** [comment]
Oh wow...

**Comment by sgdecker** [comment]
I added a comment to pydata/xarray#2534

**Comment by sgdecker** [comment]
@dopplershift The original issue became stale, but I opened a new issue, and it seems it may not be a bug on the xarray side (see https://github.com/pydata/xarray/issues/6561#issuecomment-1115419268) , but I haven't investigated this enough to understand entirely what is going on. Perhaps the way these netCDF files are being generated could be improved?

**Comment by dopplershift** [comment]
I'd say the way those netCDF data files are being generated is unmaintained at this point. If I'm not mistaken, those are running using a Perl script and some unmaintained Perl bindings for netCDF. They aren't CF-compliant and instead implement (with bugs) a linked list structure in netCDF rather than some kinda of netCDF-CF DSG sane data structure.

**Comment by sgdecker** [comment]
Yikes! My goal is to arrive at a Python-based workflow for plotting real-time surface observations to replace the LDM/GEMPAK combo. I was thinking "grab netCDF files from a TDS" might be it, but it sounds like "use LDM to save surface observations from the IDD as plain text and use parse_metar_file from MetPy" might be the way to go. I suppose there is also "use python-awips to grab data from an EDEX server", although that introduces yet another API to deal with.

**Comment by akrherz** [comment]
@sgdecker Or, my ongoing goal is to add a data access layer to metpy to allow it to hit my ASOS API for the METAR and/or atomic data, to then feed into plotting.  I continue to struggle with understanding how and where to port the Siphon bits into Metpy and what tool (pandas/geopandas/xarray) to use as a data manager within metpy for its object model.  I am sort of lazily hoping Unidata puts the scaffolding into Metpy and then I can make more managable PRs to plug in my stuff.  I dunno...

**Comment by dopplershift** [comment]
@sgdecker Here's a [Python async script](https://github.com/Unidata/ldm-alchemy/blob/metar-decode/metar2nc.py) that's meant to run with the LDM to generate netCDF files from incoming METAR reports--it ran with an older, crummier version of the MetPy parser. I haven't kept up on maintenance of it (it would periodically crash for...reasons, probably due to multithreading + netCDF). There's some niceties you could get with THREDDS in generating a netCDF CF DSG netCDF files (like getting a time series for a station), but shaking this out just hasn't been a priority. There were also attempts to add DSG<->DataFrame support in MetPy with Unidata/MetPy#1074 and Unidata/MetPy#1121, though we decided to defer to cf-xarray.

@akrherz It's on the list for sure--and we're planning on teaching an AMS short course working with some obs so we need to have more than "Download text files from thredds-*test*.unidata.ucar.edu" in place by then.

**Comment by dopplershift** [comment]
@sgdecker With all that said, unless the time of MetPy parsing the file is problematic, I would opt for the "save bulletins to a big text files, have MetPy parse" route. Given that you're running Python + MetPy either way, all netCDF gives you is a cached version of the data that's readily accessible from more tools/languages.
